[project]
name = "astrbot-plugin-history-indexer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "thefuzz>=0.22.1",
]

[tool.ruff]
target-version = "py310"
cache-dir = ".ruff_cache"
